### PR TITLE
Upgrade that motherfucker colors for a fucking correct dark mode

### PR DESCRIPTION
**Pull request by BastelPichi**
Dont fuck me for making the css 6 characters longer.

### CODE REVIEW

**Comment by LeoColomb** [comment]
Thanks for opening this PR @BastelPichi 👍 (I'll use more friendly wording on direct discussions to make sure it does not actually hurt anyone.)

I'm a bit confused because this goes against last contribution which is exactly the opposite: https://github.com/LeoColomb/perfectmotherfuckingwebsite/pull/6

Could you elaborate why do you think the new colors are better?

**Comment by BastelPichi** [comment]
Oh right. Didnt see that one.

However one of the concepts of the better motherfuckingwebsite was to have not such high contrasts, and personally i think it looks way better.
I agree, you could make the grey a bit darker, but complete black is too much. I havent seen a single app/website out there using total #000000.

**Review by LeoColomb — APPROVED** [review]

**Comment by BastelPichi** [comment]
thx, looks very good now!

**Comment by crozone** [comment]
Now the site looks terrible on OLED 😩

Can we at least drop it to #0a0c10, which is what Github dark mode uses.

> However one of the concepts of the better motherfuckingwebsite was to have not such high contrasts, and personally i think it looks way better.

Yes, and it's bad. I don't know where this idea that low contrast = more readable. Web users have become somewhat *used* to it, but it's just a [design fad, and not based on actual accessibility](https://www.nngroup.com/articles/low-contrast/).

> I havent seen a single app/website out there using total #000000.

Again, because of design trends, not actual usability. Try testing websites on an OLED display in a pitch black room. Test different brightness levels. Pure black backgrounds tend to be objectively better for eye strain in dark environments, which is what dark mode is actually designed for. Windows Phone understood this concept over a decade ago.

**Comment by BastelPichi** [comment]
> Now the site looks terrible on OLED weary
> 
> > However one of the concepts of the better motherfuckingwebsite was to have not such high contrasts, and personally i think it looks way better.
> 

> 
> > I havent seen a single app/website out there using total #000000.
> 
> Again, because of design trends, not actual usability. Try testing websites on an OLED display in a pitch black room. Test different brightness levels. Pure black backgrounds tend to be objectively better for eye strain in dark environments, which is what dark mode is actually designed for. Windows Phone understood this concept over a decade ago.

Well that is an argument, however the majority of users wont use OLED, at least for now.
> Can we at least drop it to #0a0c10, which is what Github dark mode uses.

Currently we have github colors, dont we?

> Yes, and it's bad. I don't know where this idea that low contrast = more readable. Web users have become somewhat _used_ to it, but it's just a [design fad, and not based on actual accessibility](https://www.nngroup.com/articles/low-contrast/).

While its not more readable, im sure most users would agree it looks better.

**Pull request merged**
