### PR TITLE
Fix fucking darkmode

### PR DESCRIPTION
**Pull request by crozone**
Make darkmode background black so users don't die in low-contrast grey shittiness

Seriously, look at this abomination:

image

I can barely read the text through that grey obnoxious swamp of a background.

Now look at this clean beautiful sexy perfection:

image

OLED users can thank me later.

### CODE REVIEW

**Comment by LeoColomb** [comment]
Lovely! (I prefer to keep wording more friendly on direct discussion to make sure it does not actually hurt anyone.)

The reason not to make is completely black and white was to make it more comfortable.
I agree the current grey is probably too bright, but full black might be a bit too much.

Thoughts?

**Comment by crozone** [comment]
> 
> 
> Lovely! (I prefer to keep wording more friendly on direct discussion to make sure it does not actually hurt anyone.)

Cheers for the quick response! 😍

> The reason not to make is completely black and white was to make it more comfortable.
> I agree the current grey is probably too bright, but full black might be a bit too much.
> 
> Thoughts?

I'm a sucker for pure white-on-black text (maybe because I'm an old Windows Phone stan), but I really do think it's the most legible and comfortable compared to lower contrast options. This is because it has lower overall light levels from the display, and the text is readable at much lower display brightness settings as well. I'll justify this by saying it is very different to the black-on-white text version, where there's a much stronger argument for lowering contrast to improve comfort.

Also on OLED phone displays, any shade of grey that isn't pure black tends to look... not great. Obviously not everyone is viewing websites on OLED phones, but I think there's probably a pretty large overlap with dark mode users.

However if you think the pure white-on-black is still too high contrast,maybe the text colour could be dropped down to a light grey?

Windows commandline uses #CCCCCC for its text colour:

image

And that actually looks pretty nice.

**Comment by LeoColomb** [comment]
> However if you think the pure white-on-black is still too high contrast,maybe the text colour could be dropped down to a light grey?

Good idea! 👍

**Comment by crozone** [comment]
Done!

**Comment by LeoColomb** [comment]
Fucking amazing!
Thanks 🤟

**Pull request merged**
